version: "3.8"
services:
  api:
    container_name: hexa-backend
    restart: always
    build: .
    environment:
      - PORT=${PORT}
    ports:
      - "5432:5432"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"  # Assuming 5432 is the default PostgreSQL port







