version: '3.8'
services:
  api:
    container_name: hexa-backend
    restart: always
    build: .
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT:-5432}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mysecretpassword}
      - POSTGRES_DB=${DB_NAME:-mydatabase}

volumes: 
  data: {}}
